pink/urls.py
from django.conf.urls import url
from django.contrib import admin
from pinkapp.views import *

urlpatterns = [
    url(r'^$', index , name='index'),
    url(r'^marcas$', marcas , name='marcas'),
    url(r'^indexMaster$', indexMaster , name='indexMaster'),
    url(r'^search$', search , name='search'),
    url(r'^contacto$', contacto , name='contacto'),
    url(r'^comprar$', comprar , name='comprar'),
    url(r'^compraExitosa$', compraExitosa , name='compraExitosa'),
    url(r'^detalle$', verpdf , name='detalle'),
    url(r'^login$', login , name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^master$', master , name='master'),
    url(r'^usuario$', registroUsuario, name='registroUsuario'),
    url(r'^admin/', admin.site.urls),
]

pinkapp/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Usuario(User):
    class Meta:
        proxy = True

GENERO = (
		('M','Ellos'),
		('F','Ellas'),
		('N','Ninguno'),
		)

class marca(models.Model):
	nombre = models.CharField(max_length = 120)
	imagen = models.ImageField(upload_to = 'static/uploads/')
	generoPrincipal = models.CharField(max_length = 1, choices=GENERO)
	generoSecundario = models.CharField(max_length = 1, choices=GENERO)

	class Meta:
		verbose_name = 'Marca'
		verbose_name_plural ="Marcas"

	def __unicode__(self):
		return self.nombre


class perfume(models.Model):
	nombre = models.CharField(max_length= 120)
	marca = models.ForeignKey(marca)
	precio = models.FloatField()
	presentacion = models.CharField(max_length= 120)
	generoPrincipal = models.CharField(max_length= 1, choices=GENERO)
	generoSecundario = models.CharField(max_length= 1, choices=GENERO)
	imagen = models.ImageField(upload_to = 'static/uploads/')

	class Meta:
		verbose_name = 'Perfume'
		verbose_name_plural ="Perfumes"

	def __unicode__(self):
		return self.nombre

templates/compraExitosa.html
{% extends 'template.html' %}
{%  block content %}
{% load humanize %} 
<div class="container main-container">
    <div class="jumbotron exit">
        <div class="row">
            <div class="col-md-9">
                <h1>Felicitaciones!</h1>
            <p>Tu compra de realizo con exito. En breves minutos un asesor de Perfumes Pink/826 se pondra en contacto contigo.</p>
            </div>
            <div class="col-md-3">
            <img class="img-responsive" src="static/images/carrito.png">
            </div>
        </div>
    </div>
</div>


{% endblock %}		

templates/comprar.html
{% extends 'template.html' %}
{%  block content %}
{% load humanize %} 
 <div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">
				{% if producto %}
				<div class="no-padding">
            		<span class="title">TU PRODUCTO</span>
            	</div>
        		
                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
                	<img src="{{ producto.imagen }}" class="img-responsive img" alt="Perfumes Pink">
                    <div class="caption prod-caption">
                        <h2><a href="detail.html">{{producto.nombre}}</a></h2>
                        <p><h5>{{ producto.presentacion }}</h5></p>
                        <p>
                    	<div class="btn-group">
                        	<span class="text-muted precio">${{ producto.precio|floatformat:"0"|intcomma}}</span>
                    	</div>
                        </p>
                    </div>
                </div>
		            
			</div>
				<!-- End RECENT PRODUCT -->
			
        	<div class="clearfix visible-sm"></div>
			<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">CONFIRMA TU COMPRA</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
                    <form method="POST" name="fcontacto" id="comprar" action="">
                    {% csrf_token %}
                        <label>Nombre:</label>
						<input type="text" name="name" id="name" class="form-control">
						<label>Email:</label>
						<input type="email" name="email" id="email" class="form-control">
						<label>Teléfono:</label>
						<input type="tel" name="telefono" id="telefono" class="form-control">	
						<label>Dirección:</label>
						<input type="text" name="direccion" id="direccion" class="form-control">	
    					<input type="hidden" name="producto" value={{producto.nombre}}>
                        <input type="hidden" name="precio" value={{producto.precio}}> 	    					
                    </div>
                    
					<div class="btn-group btns-cart">
						<button type="submit" id="contact" class="btn btn-primary">Confirmar</button>
					</div>

	            </div>
        	</div></div>
            {% endif %} 
        	<!-- End Cart -->
<div class="container">
  <p></p>
  <div class="alert alert-info" role="alert">
      <p class="alert-link">Puedes realizar el pago con:</p>
  </div>
            <div class="row">
                <div class="col-md-3">
                    <img href="#"class="img-responsive imgn"src="static/images/visa.png">
                </div>
                <div class="col-md-3">
                    <img href="#"class="img-responsive imgn"src="static/images/mastercard.png">
                </div>
                <div class="col-md-3">
                    <img href="#"class="img-responsive imgn"src="static/images/pagatodo.png">
                </div>
                <div class="col-md-3">
                    <img href="#"class="img-responsive imgn"src="static/images/efecty.jpg">
                </div>
            </div>

</div><!--container-->


{% endblock %}		

templates/contacto.html
{% extends 'template.html' %}
{%  block content %}

<div class="container">
<div class="jumbotron dudas">
<div class="row">
        <div class="col-md-9">
        <h1>Dudas e inquietudes</h1>
        <p>Tienes alguna duda e inquietud contactanos y en breve nuestro equipo se comunicara contigo. Tambien puedes escribirnos a nuestro Whatsapp.</p>
        </div>
        <div class="col-md-3">
		<img class="img-responsive" id="dudas" src="static/images/dudas.png">
              </div>
              </div>
              </div>
              </div>
              {% if error %}
      <div class="alert alert-danger"> {{ error }} </div>
    {% endif %}
    {% if success %}
      <div class="alert alert-success"> {{ alert }}</div>
    {% endif %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-5">
			<div class="ibody">
				<h1>Contactenos</h1>
				<div class="fcontacto">
					<form method="POST" name="fcontacto" id="fcontacto" action="">
					{% csrf_token %}
						<label>Nombre:</label>
						<input type="text" name="name" id="name" class="form-control">
						<label>Email:</label>
						<input type="email" name="email" id="email" class="form-control">
						<label>Teléfono:</label>
						<input type="tel" name="telefono" id="telefono" class="form-control">	
						<label>Asunto:</label>
						<input type="text" name="asunto" id="asunto" class="form-control">
						<label>Mensaje:</label>
						<textarea type="text" name="mensaje" id="mensaje" cols="30" rows="10" class="form-control" resize="none"></textarea> 
						<input type="submit" class"btn btn-info" id="contact" value="Enviar">
					</form>
				</div>
			</div>
		</div>
	</div>
<!---Bootstrap CSS: Formulario de Contacto (Parte 1)-->
	<div class="row">
		<div class="col-md-6 col-md-offset-4">
			<img src="static/images/icons/WhatsApp3.png" class="img-responsive" >
		</div>
	</div>
</div>
{% endblock %}		

templates/detalle.html
HOLA <strong>{{user}}</strong>

templates/footer.html
<div id="footer">
			<div class="top-area">
				<div class="container">
					<div class="row">
						<div class="col-xs-14">
							<div class="caja-redes">
							   <a href="contacto" class="icon-button pinterest"><i class="fa fa-envelope" aria-hidden="true"></i><span></span></a>
							   <a href="https://www.facebook.com/Perfumes-pink826-906183276105300/" class="icon-button facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true" ></i><span></span></a>
							   <a href="contacto" class="icon-button whatsapp"><i class="fa fa-whatsapp"></i><span></span></a>
							   <a href="#" class="icon-button google-plus"><i class="fa fa-google-plus" aria-hidden="true"></i><span></span></a>
							</div>
						</div>
					</div>	
				</div>
			</div>
		
		<div class="bottom-area">
			<div class="container">
			
				<div class="row">
					<div class="col-xs-12">
						<div class="text-center">
						COPYRIGHT© 2016 PERFUMES PINK. TODOS LOS DERECHOS RESERVADOS.
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

templates/index.html
{% extends 'template.html' %}
{%  block content %}
<div class="container">
<!-- Carousel -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1"></li>
			<li data-target="#myCarousel" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<a href="search?filter=F"><img class="first-slide" src="/static/images/products/jeanPaul.jpg" alt="First slide"></a>
			</div>
			<div class="item">
				<a href="search?filter=F&marca=34"><img class="second-slide" src="/static/images/products/nina.jpg" alt="Second slide"></a>
			</div>
			<div class="item">
				<a href="search?filter=M"><img class="third-slide" src="/static/images/products/chanel.png" alt="Third slide"></a>
			</div>
		</div>
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div><!-- /.carousel -->
	<div class="row">
		<div class="col-md-6">
			<div class="embed-responsive embed-responsive-16by9">
				<iframe width="560" height="315" src="https://www.youtube.com/embed/--PZzJlq0-A?list=PLPOMMd-_rnh_adLlAaSeW3Y4n3HvQwRin" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<div class="col-md-6">
			<a href="http://www.esika.com/pe/fragancias/suntuosa/"><img src="/static/images/mujer2.jpg" class="img-responsive imgind" id="mediaa" alt="Responsive image"></a>
		</div>
	</div>
	<div class="medios">
		<div class="row">
			<div align="center">
				<img src="/static/images/medios2.png" class="img-responsive" alt="Responsive image">
			</div>
		</div>
	</div>
</div>
{% endblock %}		

templates/indexMaster.html
{% extends 'template.html' %}
{% block content %}
        <div class="container">
             <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation"><a href="logout">Salir</a></li>
                    
                </ul>
            </nav>  
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center"></div>
                <a href="usuario">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <h1><span class="glyphicon glyphicon-user"></span></h1>
                        <h3>Registro de usuarios</h3></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="master">
                        <h1><span class="glyphicon glyphicon-pencil"></span></h1>
                        <h3>Gestionar Catalogo</h3></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center"></div>
            </div>
			</div>
{% endblock %}

templates/login.html
{% extends 'template.html' %}
{%  block content %}
<form class="registry" method="post" action="">
            {% csrf_token %}
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-3"></div>
                    <div class="col-md-5">
                        <div class="form-group"><h4>
                            <label for="exampleInputapellidos">Usuario</label>
                            <input type="text" class="form-control" name="usuario" placeholder="Usuario"></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputPassword1">Contraseña</label>
                            <input type="password" class="form-control" name="clave" placeholder="Password"></h4>
                        </div>
                        <div>
                            <p>
                                <button type="submit" class="btn btn-primary btn-lg">Ingresar</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </form>

{% endblock %}		

templates/mailCompra.html
<p><strong>Venta</strong></p>
<p><strong>Para: </strong> {{name}}</p>
<p><strong>Telefono: </strong>{{ telefono }}</p>
<p><strong>Direccion: </strong>{{ direccion }}</p>
<p><strong>Email: </strong>{{ from_email }}</p>
<p><strong>Producto: </strong>{{ producto }}</p>
<p><strong>Precio: </strong>{{ precio }}</p>

templates/marcas.html
{% extends 'template.html' %}
{%  block content %}
	<div class="container marcas">
	 <div class="row placeholders">
        <div class="col-sm-3 placeholder">
            <img src="/static/uploads/agatha.jpg" width="150" height="150" class="img-thumbnail" alt="Generic placeholder thumbnail">
            <h4 ><a href="contenido.html">nombre</a></h4>
            <span class="text-muted">$10000</span>
        </div>

    </div><!-- row -->
{% endblock %}	

templates/master.html
{% extends 'template.html' %}
{%  block content %}
<div class="container">
  <nav>
      <ul class="nav nav-pills pull-right">
          <li><a href="indexMaster"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span></a></li>
          <li role="presentation"><a href="logout">Salir</a></li>
      </ul>
  </nav>
</div>
<form class="registry" method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-5">
        <div class="form-group"><h4>
          <label for="sel1">Operación a realizar:</label>
          <select class="form-control" name="sel1" id="sel1" required>
            <option value="@">Seleccione...</option>
            <option value="mr" name="mr">Crear marca</option>
            <option value="vf" name="vf">Crear Perfume</option>
            <option value="rc" name="rc">Modificar Perfume</option>
          </select>
        </div>
        <div style ="display:none;" id="multiple">
          {% csrf_token %}
          <div class="form-group">
            {% csrf_token %}
            <fieldset class="module aligned ">
              <div class="form-row field-tipoF">
                <input class="form-control" id="id_nombre" name="tipoF" type="hidden" value="crema">
              </div>
              <div class="form-row field-nombre">
                <div>
                  <label class="required" for="id_nombre">Nombre:</label>
                  <input class="form-control" id="id_nombre" name="nombre" type="text" value="">
                </div>
              </div>
              <div class="form-row field-imagen">
                <div>
                  <label class="required" for="id_imagen">Imagen:</label>
                  <input id="id_imagen" name="imagen" type="file">
                </div>
              </div>
              <div class="form-row field-generoPrincipal">
                <div>
                  <label class="required" for="id_generoPrincipal">GeneroPrincipal:</label>
                  <select id="id_generoPrincipal" name="generoPrincipal">
                    <option value="" selected="selected">---------</option>
                    <option value="M">Ellos</option>
                    <option value="F">Ellas</option>
                    <option value="N">Ninguno</option>
                  </select>
                </div>
              </div>
              <div class="form-row field-generoSecundario">
                <div>
                  <label class="required" for="id_generoSecundario">GeneroSecundario:</label>
                  <select id="id_generoSecundario" name="generoSecundario">
                    <option value="" selected="selected">---------</option>
                    <option value="M">Ellos</option>
                    <option value="F">Ellas</option>
                    <option value="N">Ninguno</option>
                  </select>
                </div>
              </div>    
            </fieldset>
          </div>
        </div>
        <div style ="display:none;" id="crearPerfume" name="crearPerfume">
          <div class="form-group">
          {% csrf_token %}
            <fieldset class="module aligned ">
              <div class="form-row field-tipoF">
                <input class="form-control" id="id_nombre" name="tipoF" type="hidden" value="crepe">
              </div>
              <div class="form-row field-nombre">
                <div>
                  <label class="required" for="id_nombre">Nombre:</label>
                  <input class="form-control" id="id_nombre" name="nombreP" type="text" value="">
                </div>
              </div>
              <div class="form-group"><h4>
                <select class="form-control" id="ciud" name="marcaP">
                  <option value="0">Marca</option>
                  {% for marka in markas %}
                  <option value="{{ marka.id }}">{{ marka.nombre }}</option>
                  {% endfor %}
                </select></h4>
              </div>
              <div class="form-row field-precio">
                <div>
                  <label class="required" for="id_precio">Precio:</label>
                  <input class="form-control" id="id_precio" name="precioP" type="text" value="">
                </div>
              </div>
              <div class="form-row field-presentacion">
                <div>
                  <label class="required" for="id_precio">Presentación:</label>
                  <input class="form-control" id="id_presentacion" name="presentacionP" type="text" value="">
                </div>
              </div>
              <div class="form-row field-imagen">
                <div>
                  <label class="required" for="id_imagen">Imagen:</label>
                  <input id="id_imagen" name="imagenP" type="file">
                </div>
              </div>
              <div class="form-row field-generoPrincipal">
                <div>
                  <label class="required" for="id_generoPrincipal">GeneroPrincipal:</label>
                  <select id="id_generoPrincipal" name="generoPrincipalP">
                    <option value="" selected="selected">---------</option>
                    <option value="M">Ellos</option>
                    <option value="F">Ellas</option>
                    <option value="N">Ninguno</option>
                  </select>
                </div>
              </div>
              <div class="form-row field-generoSecundario">
                <div>
                  <label class="required" for="id_generoSecundario">GeneroSecundario:</label>
                  <select id="id_generoSecundario" name="generoSecundarioP">
                    <option value="" selected="selected">---------</option>
                    <option value="M">Ellos</option>
                    <option value="F">Ellas</option>
                    <option value="N">Ninguno</option>
                  </select>
                </div>
              </div>    
            </fieldset>
          </div>
        </div>
        <div style="display:none;" id="modificaperfume">
          <div class="form-group">
            <fieldset class="module aligned"><h4>
            <label class="required" for="id_generoSecundario">Referencia:</label>
              <select class="form-control" id="perfumeM" name="perfumeM">
                <option value="0">Seleccione ...</option>
                {% for perfume in perfumes %}
                <option value="{{ perfume.id }}">{{ perfume.nombre }}</option>
                {% endfor %}
              </select></h4>
              <div class="form-row field-precio">
                <div>
                  <label class="required" for="id_precio">Precio:</label>
                  <input class="form-control" id="id_precio" name="precioM" type="text" value="">
                </div>
              </div>
            </fieldset>  
          </div>
        </div>
        <br><input type="submit" id="submit" onclick="javascript:document.getElementById('formPrincipal').submit();"class="btn btn-primary" />  
      </div>
    </div>
  </div>
</form>

  
<script>
  document.getElementById("sel1").onchange = mostrar;
  function mostrar()
  {
    document.getElementById("multiple").style.display = "none";
    document.getElementById("crearPerfume").style.display = "none";
    document.getElementById("modificaperfume").style.display = "none";

    if(document.getElementById("sel1").value == "mr")
     document.getElementById("multiple").style.display = "block";

   else if(document.getElementById("sel1").value == "vf")
     document.getElementById("crearPerfume").style.display = "block";

   else if (document.getElementById("sel1").value == "rc")
    document.getElementById("modificaperfume").style.display = "block";
  }
</script>
{% endblock %}		

templates/search.html
{% extends 'template.html' %}

{%  block content %}
{% load humanize %} 
<div class="container marcas">
	<div class="alert alert-success" role="alert">
		{% if lista.count == 1 %}
		<p class="alert-link">Resultado encontrado por "{{ filtro }}"  {{ lista.count }} disponible</p>

		{% elif lista.count > 1 %}
		<p class="alert-link"> {{ lista.Page.object_list }} Resultados encontrados </p>
		{% else %}
		<p class="alert-link">No se encontraron resultados</p>
		{% endif %}
	</div>
	{% if detalle == True %}
		<div class="row placeholders">
	       {% for perfume in lista %}
		        <div class="col-md-3 placeholder">
		            <img src="{{ perfume.imagen }}" class="img-responsive img" alt="Perfumes Pink"> 
		            <h3 >{{ perfume.nombre }}</h3>
		            <span class="text-muted presentacion">{{ perfume.presentacion }}</span><br>	
		            <span class="text-muted precio">

		            ${{ perfume.precio|floatformat:"0"|intcomma }} </span><a href="comprar?filter={{ perfume.id }}" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Comprar</a>
		        </div>
	        {% endfor %}
	    </div><!-- row -->
     {% else%}
	     <div class="row placeholders">
	       {% for marca in lista %}
		        <div class="col-md-3 placeholder">
		        	<a href="search?filter={{ filtro }}&marca={{ marca.id }}">
		            <img src="{{ marca.imagen }}" class="img-responsive img" alt="Perfumes Pink">        
		        </div>
	        {% endfor %}
	    </div><!-- row -->
    {% endif %}
	<div class="pagination-centered">
		<nav>
			<ul class="pagination">
				<li>
					{% if marcas.has_previous %}
						<a href="{% url 'search' %}?filter={{filtro}}&page={{ marcas.previous_page_number }}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						</a>
					{% else %}
						<a href="{% url 'search' %}?filter={{filtro}}&page=1" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						</a>
					{% endif %}
				</li>
				{% for page in paginador.page_range %}
					<li><a href="{% url 'search' %}?filter={{filtro}}&page={{ page }}">{{ page}}</a></li>
				{% endfor %}
				<li>
					{% if marcas.has_next %}
						<a href="{% url 'search' %}?filter={{filtro}}&page={{ marcas.next_page_number }}" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
						</a>
					{% else %}
						<a href="{% url 'search' %}?filter={{filtro}}&page={{ paginador.num_pages }}" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
						</a>
					{% endif%}
				</li>
			</ul>
		</nav>
	</div><!-- container -->
</div>

{% endblock %}

templates/template.html
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Perfumes Pink</title>
		<link rel="shortcut icon" href="/static/images/icons/favicon.ico">
		<link rel="stylesheet" href="/static/css/main.css" type="text/css"/>
		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/css/carousel.css" rel="stylesheet">
		<link href="/static/css/font-awesome.css" rel="stylesheet">
		<link href="/static/css/estilos.css" rel="stylesheet">		
	</head>
<body>
	<div class="the-background">
		<div id="header" class="sdnavbar-fixed-top">
			<nav class="navbar">
				<div class="container relative">
					<div class="row">
						<div class="col-xs-12">
							<div class="row">
								<div class="col-sm-6  col-xs-8">
									<div class="logo">
										<a href="{% url 'index' %}"><img class="img-responsive" src="/static/images/lg.png" alt="Perfumes Pink"/></a>
									</div>
								</div>
								<div class="col-sm-6 col-xs-4">
									<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-1"></div>

						<div class="navbar-collapse collapse">
						<!--Css 7288-->
							<ul class="nav navbar-nav menu">
	    				    	<li class="is-bold"><a href="search?filter=F">Perfumes para Mujer</a></li>		
						    	<li class="is-bold"><a href="search?filter=M">Perfumes para hombre</a></li>	
						    	<li class="is-bold"><a href="#">Ultraconcetrados</a></li>
						    	<li class="is-bold"><a href="contacto">Contactenos</a></li>
						    	<li class="is-bold"><a href="login"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></a></li>
					    	</ul>
						</div>
					</div>
				</div>
			</nav>
		</div>
	</div>
	{%  block content %}

  	{% endblock %}

  {% include 'footer.html' %}
<script type="text/javascript" src="/static/js/main.js" charset="utf-8"></script>

  	{% block javascript %}

	{% endblock %}


</body>
</html>

templates/usuario.html
{% extends 'template.html' %}
{%  block content %}
        <div class="container">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li><a href="indexMaster"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span></a></li>
                    <li role="presentation"><a href="logout">Salir</a></li>
                </ul>
            </nav>
            <div class="starter-template">
                <h1 align="center">Registro de Usuarios</h1>
                <p class="lead">Registre a continuacion los usuarios que tendran acceso a la plataforma. Asigne el perfil que tendra el usuario:<br>
                </p>
            </div>
            {% if error %}
      <div class="alert alert-danger"> {{ error }} </div>
    {% endif %}
    {% if success %}
      <div class="alert alert-success"> Nuevo usuario creado con éxito!</div>
    {% endif %}
    </div><!-- /.container -->
		<form class="registry" method="post" action="">
            {% csrf_token %}
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-3"></div>
                    <div class="col-md-5">

                        <div class="form-group"><h4>
                            <label for="exampleInputnomre">Nombre</label>
                            <input type="text" class="form-control" name="nombre" placeholder="Nombre" required></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputapellidos">Apellidos</label>
                            <input type="text" class="form-control" name="apellidos" placeholder="Apellidos" required></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputapellidos">Cedula</label>
                            <input type="text" class="form-control" name="cedula" placeholder="Numero de cedula" required></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputEmail1">Correo electronico</label>
                            <input type="email" class="form-control" name="email" placeholder="Email" required></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputPassword1">Constraseña</label>
                            <input type="password" class="form-control" name="password" placeholder="Password" required></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputPassword1">Confirma tu contraseña</label>
                            <input type="password" class="form-control" name="repassword" placeholder="Password" required></h4>
                        </div>
                        <div class="form-group"><h4>
                            <label for="exampleInputapellidos">Permisos</label>
                            <select required name="perfil" class="form-control" >
                                <option selected disabled>Seleccione Perfil</option>
                                <option value="1">Administrador</option>
                                <option value="3">Consultor</option>
                                <option value="2">Auxiliar</option>
                            </select></h4>
                        </div>
                        <div>
                            <p>
                                <button type="submit" class="btn btn-primary btn-lg">Registrar</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </form>
{% endblock %}